version: '3.8'

services:
  localstack:
    image: localstack/localstack:3.0.0
    ports:
      - "4566:4566"
    environment:
      - SERVICES=sqs
      - DEFAULT_REGION=us-east-1
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - DEBUG=1
      - DOCKER_HOST=unix:///var/run/docker.sock
      - SQS_QUEUE_NAME=my-test-queue
    volumes:
      - ./localstack:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock
      - ./init-aws.sh:/etc/localstack/init/ready.d/init-aws.sh

  postgres:
    image: postgres:15.17-alpine3.22
    container_name: postgres-db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: spt1234
      POSTGRES_DB: sptech-db-sqs
    volumes:
      - db_data:/var/lib/postgresql/data

  hogmail:
    image: axllent/mailpit
    container_name: hogmail
    ports:
      - "8025:8025"
      - "1025:1025"

volumes:
  db_data:
