
spring.datasource.url=jdbc:mysql://localhost:3306/usersdb
spring.datasource.username=root
spring.datasource.password=vivo8642*
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

sqs.endpoint=http://localhost:4566
sqs.queue-name=my-test-queue

spring.main.allow-bean-definition-overriding=true
