server.port=8090
spring.datasource.url=jdbc:postgresql://localhost:5433/sptech-db-sqs
spring.datasource.username=postgres
spring.datasource.password=spt1234
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

sqs.endpoint=http://localhost:4566
sqs.queue-name=sptech-test-queue

spring.main.allow-bean-definition-overriding=true
